[package]
name = "triton-vm"
version = "0.20.0"
edition = "2021"
authors = ["Triton Software AG"]

license = "Apache-2.0"
description = """
A virtual machine that comes with Algebraic Execution Tables (AET) and Arithmetic Intermediate Representations (AIR)
for use in combination with a STARK proof system to allow proving correct execution of arbitrary programs
in zero-knowledge.
"""
homepage = "https://triton-vm.org/"
documentation = "https://github.com/TritonVM/triton-vm/tree/master/specification"
repository = "https://github.com/TritonVM/triton-vm"
readme = "../README.md"

keywords = ["zero-knowledge", "STARK", "virtual-machine", "recursive"]
categories = ["cryptography", "mathematics"]

[dev-dependencies]
proptest = "1.0"

[dev-dependencies.criterion]
version = "0.4.0"
features = ["html_reports"]

[dev-dependencies.cargo-husky]
version = "1"
default-features = false

[dependencies]
twenty-first = "0.21.1"
triton-opcodes = {path = "../triton-opcodes"}
triton-zmips = {path = "../triton-zmips"}
triton-profiler = {path = "../triton-profiler"}
triton-program = {path = "../triton-program"}
anyhow = "1.0"
bincode = "1.3"
itertools = "0.10.5"
num-traits = "0.2"
rand = "0.8.5"
rand_core = "0.6.4"
rayon = "1.5"
serde = { version = "1.0", features = ["derive"] }
strum = "0.24"
strum_macros = "0.24"
ndarray = { version = "0.15", features = ["rayon"] }

[[bench]]
name = "prove_halt"
harness = false

[[bench]]
name = "prove_fib_100"
harness = false

[[bench]]
name = "verify_halt"
harness = false
